-- Deprecated: this file has moved.
-- Use the canonical script under FlibustaSQL/generate_book_mappings.sql.
-- The backend defaults to /app/sql/populate_book_mappings.sql via MAPPINGS_SQL_PATH.
-- Keeping this stub to avoid breaking links during deprecation window.
